config/routes.rb
Rails.application.routes.draw do
  # ---LAST EXCERCISE ROUTES---
  resources :friends #this translates to all the CRUD routes
  get 'home/about'
  #root 'home#index'
  # ---END OF LAST EXCERCISE ROUTES---
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new] 
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        #params is where all the parameters are allocated
        #in order to make the variable available in all the app yo need to make it an instance with "@"
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was created successfully"
            #How this redirect works?
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    # Only allow a list of trusted parameters through.
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def set_article
        @article = Article.find(params[:id])
      end

    def require_same_user
        if current_user != @article.user
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
end

app/views/articles/_article.html.erb
<div id="articles">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Author</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Categories</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @articles.each do |article| %>
                <tr>
                    <td><%= link_to article.user.username, user_path(article.user) %></td>
                    <td><%= article.title %></td>
                    <td><%= article.description%></td>
                    <td><%= render article.categories %></td>
                    <td><%= link_to 'Show', article_path(article) %></td>
                    <% if logged_in? && article.user == current_user %>
                        <td><%= button_to 'Delete', article_path(article), method: :delete %></td>
                        <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to "Create new article", new_article_path %>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<% if @article.errors.any? %>
    <h3>Errors creating the article:</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<!-- The form_with(model: @article) automatically knows to submit to the update action-->
<%= form_with(model: @article, local:true) do |f|%>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :category %>
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
        { prompt: "Select categories"}, { multiple: true }) %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1>Create new article</h1>
<% if @article.errors.any? %>
    <h3>Errors creating the article:</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f|%>
    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :category %>
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
        { prompt: "Select categories"}, { multiple: true }) %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Author: </strong><%= @article.user.username %></p>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<% if @article.categories.any? %>
    <p><strong>Categories:</strong><%= render @article.categories %></p>
<% end %>
<% if logged_in? && @article.user == current_user %>
    <%= link_to "Edit", edit_article_path(@article.id) %> |
    <%= link_to "Delete", article_path(@article.id), method: :delete %> |
<% end %>
<%= link_to "Return to articles listings", articles_path %>