config/routes.rb
Rails.application.routes.draw do
  # ---LAST EXCERCISE ROUTES---
  resources :friends #this translates to all the CRUD routes
  get 'home/about'
  #root 'home#index'
  # ---END OF LAST EXCERCISE ROUTES---
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new] 
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>  <!-- use rails link_to -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'About us', home_about_path, class:"nav-link" %>  <!-- home_about_path we always add path at the end-->
        </li>
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Create new article", new_article_path, class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "View articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'Users', users_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'Add Friends', new_friend_path, class:"nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Log out', logout_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Delete profile', user_path(current_user), method: :delete, class:"nav-link" %>
          </li>
        <% else %>
        <li class="nav-item">
         <%= link_to 'Log in', login_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to 'Sing up', signup_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Hello World</h1>