config/routes.rb
Rails.application.routes.draw do
  # ---LAST EXCERCISE ROUTES---
  resources :friends #this translates to all the CRUD routes
  get 'home/about'
  #root 'home#index'
  # ---END OF LAST EXCERCISE ROUTES---
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new] 
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end
    
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 4)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    private
    
    def category_params
        params.require(:category).permit(:name)
    end
end

app/views/categories/_category.html.erb
<%= link_to ' │ ' +  category.name + ' │ ', category_path(category) %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'shared/errors', obj: @category %>
            <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
            <div class="form-group row">
                <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
                <div class="col-10">
                <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
                </div>
            </div>

            <div class="form-group row justify-content-center">
                <%= f.submit class: "btn btn-outline-light btn-lg" %>
            </div>
        <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div id="categories">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Articles</th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td><%= link_to category.name, category_path(category) %></td>
                    <td><%= pluralize(category.articles.count, "article") %></td>
                    
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to "Create new category", new_category_path %>
</div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
<div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
</div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render "articles/article" %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>